import * as vscode from 'vscode';
import { AbascCompletionInfo } from './abasccompletioninfo';

export const CPCRSLIBInfo: AbascCompletionInfo[] = [
{
        label: "rsDisableFirmware",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/firmware.bas",
        signature: "SUB rsDisableFirmware",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsDisableFirmware"),
    },
    {
        label: "rsEnableFirmware",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/firmware.bas",
        signature: "SUB rsEnableFirmware",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsEnableFirmware"),
    },
    {
        label: "rsAnyKeyPressed",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/keyboard.bas",
        signature: "FUNCTION rsAnyKeyPressed",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsAnyKeyPressed"),
    },
    {
        label: "rsAssignKey",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/keyboard.bas",
        signature: "SUB rsAssignKey(entry, keyid)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsAssignKey(${1:entry}, ${2:keyid})"),
    },
    {
        label: "rsDeleteKeys",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/keyboard.bas",
        signature: "SUB rsDeleteKeys",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsDeleteKeys"),
    },
    {
        label: "rsRedefineKey",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/keyboard.bas",
        signature: "SUB rsRedefineKey(entry)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsRedefineKey(${1:entry})"),
    },
    {
        label: "rsScanKeyboard",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/keyboard.bas",
        signature: "SUB rsScanKeyboard",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsScanKeyboard"),
    },
    {
        label: "rsTestKey",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/keyboard.bas",
        signature: "FUNCTION rsTestKey(entry)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsTestKey(${1:entry})"),
    },
    {
        label: "rsTestKeyF",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/keyboard.bas",
        signature: "FUNCTION rsTestKeyF(entry)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsTestKeyF(${1:entry})"),
    },
    {
        label: "rsTestKeyboard",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/keyboard.bas",
        signature: "FUNCTION rsTestKeyboard(kbline)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsTestKeyboard(${1:kbline})"),
    },
    {
        label: "rsWyzConfigurePlayer",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/player.bas",
        signature: "SUB rsWyzConfigurePlayer(bitflags)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsWyzConfigurePlayer(${1:bitflags})"),
    },
    {
        label: "rsWyzInitPlayer",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/player.bas",
        signature: "SUB rsWyzInitPlayer(songstable, effectstable, rulestable, soundstable)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsWyzInitPlayer(${1:songstable}, ${2:effectstable}, ${3:rulestable}, ${4:soundstable})"),
    },
    {
        label: "rsWyzLoadSong",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/player.bas",
        signature: "SUB rsWyzLoadSong(song)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsWyzLoadSong(${1:song})"),
    },
    {
        label: "rsWyzSetTempo",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/player.bas",
        signature: "SUB rsWyzSetTempo(tempo)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsWyzSetTempo(${1:tempo})"),
    },
    {
        label: "rsWyzStartEffect",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/player.bas",
        signature: "SUB rsWyzStartEffect(channel, effect)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsWyzStartEffect(${1:channel}, ${2:effect})"),
    },
    {
        label: "rsWyzTestPlayer",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/player.bas",
        signature: "FUNCTION rsWyzTestPlayer",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsWyzTestPlayer"),
    },
    {
        label: "rsWyzSetPlayerOn",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/player.bas",
        signature: "SUB rsWyzSetPlayerOn",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsWyzSetPlayerOn"),
    },
    {
        label: "rsWyzSetPlayerOff",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/player.bas",
        signature: "SUB rsWyzSetPlayerOff",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsWyzSetPlayerOff"),
    },
    {
        label: "rsCollSp",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/sprite.bas",
        signature: "FUNCTION rsCollSp(sprite1$, sprite2$)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsCollSp(${1:recordsp1}, ${2:recordsp2})"),
    },
    {
        label: "rsGetSp",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/sprite.bas",
        signature: "SUB rsGetSp(buf, w, h, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsGetSp(${1:buf}, ${2:w}, ${3:h}, ${4:vmem})"),
    },
    {
        label: "rsGetSpXY",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/sprite.bas",
        signature: "SUB rsGetSpXY(buf, w, h, x, y)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsGetSpXY(${1:buf}, ${2:w}, ${3:h}, ${4:x}, ${5:y})"),
    },
    {
        label: "rsPutSp",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/sprite.bas",
        signature: "SUB rsPutSp(sprite$, w, h, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPutSp(${1:recordsp}, ${2:w}, ${3:h}, ${4:vmem})"),
    },
    {
        label: "rsPutSpXY",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/sprite.bas",
        signature: "SUB rsPutSpXY(sprite, w, h, x, y)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPutSpXY(${1:recordsp, ${2:w}, ${3:h}, ${4:x}, ${5:y})"),
    },
    {
        label: "rsPutSpXOR",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/sprite.bas",
        signature: "SUB rsPutSpXOR(sprite, w, h, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPutSpXOR(${1:recordsp}, ${2:w}, ${3:h}, ${4:vmem})"),
    },
    {
        label: "rsPutSpXORXY",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/sprite.bas",
        signature: "SUB rsPutSpXORXY(sprite, w, h, x, y)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPutSpXORXY(${1:recordsp}, ${2:w}, ${3:h}, ${4:x}, ${5:y})"),
    },
    {
        label: "rsPrintGphStrStd",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/text.bas",
        signature: "SUB rsPrintGphStrStd(npen, text$, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPrintGphStrStd(${1:npen}, ${2:text}, ${3:vmem})"),
    },
    {
        label: "rsPrintGphStrStdXY",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/text.bas",
        signature: "SUB rsPrintGphStrStdXY(npen, text$, x, y)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPrintGphStrStdXY(${1:npen}, ${1:text}, ${1:x}, ${1:y})"),
    },
    {
        label: "rsPrintGphStrM0",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/text.bas",
        signature: "SUB rsPrintGphStrM0(text$, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPrintGphStrM0(${1:text}, ${2:vmem})"),
    },
    {
        label: "rsPrintGphStrXYM0",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/text.bas",
        signature: "SUB rsPrintGphStrXYM0(text$, x, y)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPrintGphStrXYM0(${1:text}, ${2:x}, ${3:y})"),
    },
    {
        label: "rsPrintGphStrM0x2",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/text.bas",
        signature: "SUB rsPrintGphStrM0x2(text$, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPrintGphStrM0x2(${1:text}, ${2:vmem})"),
    },
    {
        label: "rsPrintGphStrXYM0x2",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/text.bas",
        signature: "SUB rsPrintGphStrXYM0x2(text$, x, y)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPrintGphStrXYM0x2(${1:text}, ${2:x}, ${3:y})"),
    },
    {
        label: "rsPrintGphStrM1",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/text.bas",
        signature: "SUB rsPrintGphStrM1(text$, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPrintGphStrM1(${1:text}, ${2:vmem})"),
    },
    {
        label: "rsPrintGphStrXYM1",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/text.bas",
        signature: "SUB rsPrintGphStrXYM1(text$, x, y)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPrintGphStrXYM1(${1:text}, ${2:x}, ${3:y})"),
    },
    {
        label: "rsPrintGphStrM1x2",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/text.bas",
        signature: "SUB rsPrintGphStrM1x2(text$, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPrintGphStrM1x2(${1:text}, ${2:vmem})"),
    },
    {
        label: "rsPrintGphStrXYM1x2",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/text.bas",
        signature: "SUB rsPrintGphStrXYM1x2(text$, x, y)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPrintGphStrXYM1x2(${1:text}, ${2:x}, ${3:y})"),
    },
    {
        label: "rsSetInkGphStrM0",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/text.bas",
        signature: "SUB rsSetInkGphStrM0(indind, color)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsSetInkGphStrM0(${1:indind}, ${2:color})"),
    },
    {
        label: "rsSetInkGphStrM1",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/text.bas",
        signature: "SUB rsSetInkGphStrM1(indind, color)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsSetInkGphStrM1(${1:indind}, ${2:color})"),
    },
    {
        label: "rsInitTileMap",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/tilemap.bas",
        signature: "SUB rsInitTileMap",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsInitTileMap"),
    },
    {
        label: "rsSetTile",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/tilemap.bas",
        signature: "SUB rsSetTile(x, y, tile)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsSetTile(${1:x}, ${2:y}, ${3:tile})"),
    },
    {
        label: "rsReadTile",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/tilemap.bas",
        signature: "FUNCTION rsReadTile(x, y)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsReadTile(${1:x}, ${2:y})"),
    },
    {
        label: "rsShowTileMap",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/tilemap.bas",
        signature: "SUB rsShowTileMap",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsShowTileMap"),
    },
    {
        label: "rsShowTileMap2",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/tilemap.bas",
        signature: "SUB rsShowTileMap2",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsShowTileMap2"),
    },
    {
        label: "rsResetTouchedTiles",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/tilemap.bas",
        signature: "SUB rsResetTouchedTiles",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsResetTouchedTiles"),
    },
    {
        label: "rsPutSpTileMap",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/tilemap.bas",
        signature: "SUB rsPutSpTileMap(rssprite$)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPutSpTileMap(${1:recordsp})"),
    },
    {
        label: "rsUpdScr",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/tilemap.bas",
        signature: "SUB rsUpdScr",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsUpdScr"),
    },
    {
        label: "rsPutSpTileMap2b",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/tilemap.bas",
        signature: "SUB rsPutSpTileMap2b(rssprite$)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPutSpTileMap2b(${1:recordsp})"),
    },
    {
        label: "rsPutMaskSpTileMap2b",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/tilemap.bas",
        signature: "SUB rsPutMaskSpTileMap2b(rssprite$)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPutMaskSpTileMap2b(${1:recordsp})"),
    },
    {
        label: "rsUpdTileTable",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/tilemap.bas",
        signature: "SUB rsUpdTileTable(x, y)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsUpdTileTable(${1:x}, ${2:y})"),
    },
    {
        label: "rsGetDoubleBufferAddress",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/tilemap.bas",
        signature: "FUNCTION rsGetDoubleBufferAddress(x, y)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsGetDoubleBufferAddress(${1:x}, ${2:y})"),
    },
    {
        label: "rsScrollLeft00",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/tilemap.bas",
        signature: "SUB rsScrollLeft00",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsScrollLeft00"),
    },
    {
        label: "rsScrollRight00",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/tilemap.bas",
        signature: "SUB rsScrollRight00",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsScrollRight00"),
    },
    {
        label: "rsPause",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/utils.bas",
        signature: "SUB rsPause(halts)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsPause(${1:halts})"),
    },
    {
        label: "rsRandom",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/utils.bas",
        signature: "FUNCTION rsRandom",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsRandom"),
    },
    {
        label: "rsWaitVSync",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/utils.bas",
        signature: "SUB rsWaitVSync",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsWaitVSync"),
    },
    {
        label: "rsClrScr",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/video.bas",
        signature: "SUB rsClrScr",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsClrScr"),
    },
    {
        label: "rsGetScrAddress",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/video.bas",
        signature: "FUNCTION rsGetScrAddress(x, y)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsGetScrAddress(${1:x}, ${2:y})"),
    },
    {
        label: "rsRLI",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/video.bas",
        signature: "SUB rsRLI(vmem, w, h)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsRLI(${1:vmem}, ${2:w}, ${3:h})"),
    },
    {
        label: "rsRRI",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/video.bas",
        signature: "SUB rsRRI(vmem, w, h)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsRRI(${1:vmem}, ${2:w}, ${3:h})"),
    },
    {
        label: "rsSetColour",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/video.bas",
        signature: "SUB rsSetColour(npen, hwcolour)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsSetColour(${1:npen}, ${2:hwcolour})"),
    },
    {
        label: "rsSetMode",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpcrslib/video.bas",
        signature: "SUB rsSetMode(nmode)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("rsSetMode(${1:nmode})"),
    },
    {
        label: "RSKEY.EMPTY",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.EMPTY",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.EMPTY"),
    },
    {
        label: "RSKEY.FDOT",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.FDOT",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.FDOT"),
    },
    {
        label: "RSKEY.FENTER",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.FENTER",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.FENTER"),
    },
    {
        label: "RSKEY.F3",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.F3",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.F3"),
    },
    {
        label: "RSKEY.F6",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.F6",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.F6"),
    },
    {
        label: "RSKEY.F9",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.F9",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.F9"),
    },
    {
        label: "RSKEY.DOWN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.DOWN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.DOWN"),
    },
    {
        label: "RSKEY.RIGHT",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.RIGHT",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.RIGHT"),
    },
    {
        label: "RSKEY.UP",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.UP",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.UP"),
    },
    {
        label: "RSKEY.F0",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.F0",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.F0"),
    },
    {
        label: "RSKEY.F2",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.F2",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.F2"),
    },
    {
        label: "RSKEY.F1",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.F1",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.F1"),
    },
    {
        label: "RSKEY.F5",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.F5",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.F5"),
    },
    {
        label: "RSKEY.F8",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.F8",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.F8"),
    },
    {
        label: "RSKEY.F7",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.F7",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.F7"),
    },
    {
        label: "RSKEY.COPY",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.COPY",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.COPY"),
    },
    {
        label: "RSKEY.LEFT",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.LEFT",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.LEFT"),
    },
    {
        label: "RSKEY.CTRL",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.CTRL",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.CTRL"),
    },
    {
        label: "RSKEY.BSLASH",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.BSLASH",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.BSLASH"),
    },
    {
        label: "RSKEY.SHIFT",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.SHIFT",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.SHIFT"),
    },
    {
        label: "RSKEY.F4",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.F4",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.F4"),
    },
    {
        label: "RSKEY.RSQUARE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.RSQUARE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.RSQUARE"),
    },
    {
        label: "RSKEY.RETURN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.RETURN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.RETURN"),
    },
    {
        label: "RSKEY.LSQUARE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.LSQUARE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.LSQUARE"),
    },
    {
        label: "RSKEY.CLR",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.CLR",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.CLR"),
    },
    {
        label: "RSKEY.DOT",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.DOT",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.DOT"),
    },
    {
        label: "RSKEY.FSLASH",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.FSLASH",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.FSLASH"),
    },
    {
        label: "RSKEY.COLON",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.COLON",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.COLON"),
    },
    {
        label: "RSKEY.SCOLON",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.SCOLON",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.SCOLON"),
    },
    {
        label: "RSKEY.P",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.P",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.P"),
    },
    {
        label: "RSKEY.AT",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.AT",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.AT"),
    },
    {
        label: "RSKEY.MINUS",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.MINUS",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.MINUS"),
    },
    {
        label: "RSKEY.EXP",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.EXP",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.EXP"),
    },
    {
        label: "RSKEY.COMMA",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.COMMA",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.COMMA"),
    },
    {
        label: "RSKEY.M",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.M",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.M"),
    },
    {
        label: "RSKEY.K",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.K",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.K"),
    },
    {
        label: "RSKEY.L",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.L",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.L"),
    },
    {
        label: "RSKEY.I",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.I",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.I"),
    },
    {
        label: "RSKEY.O",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.O",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.O"),
    },
    {
        label: "RSKEY.9",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.9",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.9"),
    },
    {
        label: "RSKEY.0",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.0",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.0"),
    },
    {
        label: "RSKEY.SPACE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.SPACE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.SPACE"),
    },
    {
        label: "RSKEY.N",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.N",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.N"),
    },
    {
        label: "RSKEY.J",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.J",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.J"),
    },
    {
        label: "RSKEY.H",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.H",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.H"),
    },
    {
        label: "RSKEY.Y",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.Y",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.Y"),
    },
    {
        label: "RSKEY.U",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.U",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.U"),
    },
    {
        label: "RSKEY.7",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.7",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.7"),
    },
    {
        label: "RSKEY.8",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.8",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.8"),
    },
    {
        label: "RSKEY.V",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.V",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.V"),
    },
    {
        label: "RSKEY.B",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.B",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.B"),
    },
    {
        label: "RSKEY.F",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.F",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.F"),
    },
    {
        label: "RSKEY.G",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.G",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.G"),
    },
    {
        label: "RSKEY.T",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.T",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.T"),
    },
    {
        label: "RSKEY.R",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.R",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.R"),
    },
    {
        label: "RSKEY.5",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.5",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.5"),
    },
    {
        label: "RSKEY.6",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.6",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.6"),
    },
    {
        label: "RSKEY.J2FIRE3",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.J2FIRE3",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.J2FIRE3"),
    },
    {
        label: "RSKEY.J2FIRE2",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.J2FIRE2",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.J2FIRE2"),
    },
    {
        label: "RSKEY.J2FIRE1",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.J2FIRE1",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.J2FIRE1"),
    },
    {
        label: "RSKEY.J2RIGHT",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.J2RIGHT",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.J2RIGHT"),
    },
    {
        label: "RSKEY.J2LEFT",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.J2LEFT",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.J2LEFT"),
    },
    {
        label: "RSKEY.J2DOWN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.J2DOWN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.J2DOWN"),
    },
    {
        label: "RSKEY.J2UP",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.J2UP",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.J2UP"),
    },
    {
        label: "RSKEY.X",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.X",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.X"),
    },
    {
        label: "RSKEY.C",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.C",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.C"),
    },
    {
        label: "RSKEY.D",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.D",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.D"),
    },
    {
        label: "RSKEY.S",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.S",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.S"),
    },
    {
        label: "RSKEY.W",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.W",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.W"),
    },
    {
        label: "RSKEY.E",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.E",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.E"),
    },
    {
        label: "RSKEY.3",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.3",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.3"),
    },
    {
        label: "RSKEY.4",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.4",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.4"),
    },
    {
        label: "RSKEY.Z",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.Z",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.Z"),
    },
    {
        label: "RSKEY.CAPS",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.CAPS",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.CAPS"),
    },
    {
        label: "RSKEY.A",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.A",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.A"),
    },
    {
        label: "RSKEY.TAB",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.TAB",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.TAB"),
    },
    {
        label: "RSKEY.Q",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.Q",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.Q"),
    },
    {
        label: "RSKEY.ESC",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.ESC",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.ESC"),
    },
    {
        label: "RSKEY.2",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.2",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.2"),
    },
    {
        label: "RSKEY.1",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.1",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.1"),
    },
    {
        label: "RSKEY.DEL",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.DEL",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.DEL"),
    },
    {
        label: "RSKEY.J1FIRE3",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.J1FIRE3",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.J1FIRE3"),
    },
    {
        label: "RSKEY.J1FIRE2",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.J1FIRE2",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.J1FIRE2"),
    },
    {
        label: "RSKEY.J1FIRE1",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.J1FIRE1",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.J1FIRE1"),
    },
    {
        label: "RSKEY.J1RIGHT",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.J1RIGHT",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.J1RIGHT"),
    },
    {
        label: "RSKEY.J1LEFT",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.J1LEFT",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.J1LEFT"),
    },
    {
        label: "RSKEY.J1DOWN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.J1DOWN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.J1DOWN"),
    },
    {
        label: "RSKEY.J1UP",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKEY.J1UP",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKEY.J1UP"),
    },
    {
        label: "RSKB.LINE1",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKB.LINE1",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKB.LINE1"),
    },
    {
        label: "RSKB.LINE2",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKB.LINE2",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKB.LINE2"),
    },
    {
        label: "RSKB.LINE3",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKB.LINE3",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKB.LINE3"),
    },
    {
        label: "RSKB.LINE4",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKB.LINE4",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKB.LINE4"),
    },
    {
        label: "RSKB.LINE5",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKB.LINE5",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKB.LINE5"),
    },
    {
        label: "RSKB.LINE6",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKB.LINE6",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKB.LINE6"),
    },
    {
        label: "RSKB.LINE7",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKB.LINE7",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKB.LINE7"),
    },
    {
        label: "RSKB.LINE8",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKB.LINE8",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKB.LINE8"),
    },
    {
        label: "RSKB.LINE9",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKB.LINE9",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKB.LINE9"),
    },
    {
        label: "RSKB.LINE10",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/keyboard.bas",
        signature: "CONST RSKB.LINE10",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSKB.LINE10"),
    },
    {
        label: "RSCH.A",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/player.bas",
        signature: "CONST RSCH.A",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSCH.A"),
    },
    {
        label: "RSCH.B",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/player.bas",
        signature: "CONST RSCH.B",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSCH.B"),
    },
    {
        label: "RSCH.C",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/player.bas",
        signature: "CONST RSCH.C",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSCH.C"),
    },
    {
        label: "RSPRITE.SIZE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/sprite.bas",
        signature: "CONST RSPRITE.SIZE = 14",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSPRITE.SIZE"),
    },
    {
        label: ".rssp.sp0",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/sprite.bas",
        signature: "RECORD rssp; sp0, sp1, vmem0, vmem1, cpos, opos, movdir",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString(".rssp.sp0"),
    },
    {
        label: ".rssp.sp1",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/sprite.bas",
        signature: "CONST RECORD rssp; sp0, sp1, vmem0, vmem1, cpos, opos, movdir",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString(".rssp.sp1"),
    },
    {
        label: ".rssp.vmem0",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/sprite.bas",
        signature: "CONST RECORD rssp; sp0, sp1, vmem0, vmem1, cpos, opos, movdir",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString(".rssp.vmem0"),
    },
    {
        label: ".rssp.vmem1",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/sprite.bas",
        signature: "CONST RECORD rssp; sp0, sp1, vmem0, vmem1, cpos, opos, movdir",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString(".rssp.vmem1"),
    },
    {
        label: ".rssp.cpos",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/sprite.bas",
        signature: "CONST RECORD rssp; sp0, sp1, vmem0, vmem1, cpos, opos, movdir",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString(".rssp.cpos"),
    },
    {
        label: ".rssp.opos",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/sprite.bas",
        signature: "CONST RECORD rssp; sp0, sp1, vmem0, vmem1, cpos, opos, movdir",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString(".rssp.opos"),
    },
    {
        label: ".rssp.movdir",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/sprite.bas",
        signature: "CONST RECORD rssp; sp0, sp1, vmem0, vmem1, cpos, opos, movdir",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString(".rssp.movdir"),
    },
    {
        label: "RSTXT0.PEN0",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT0.PEN0",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT0.PEN0"),
    },
    {
        label: "RSTXT0.PEN1",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT0.PEN1",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT0.PEN1"),
    },
    {
        label: "RSTXT0.PEN2",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT0.PEN2",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT0.PEN2"),
    },
    {
        label: "RSTXT0.PEN3",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT0.PEN3",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT0.PEN3"),
    },
    {
        label: "RSTXT0.PEN4",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT0.PEN4",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT0.PEN4"),
    },
    {
        label: "RSTXT0.PEN5",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT0.PEN5",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT0.PEN5"),
    },
    {
        label: "RSTXT0.PEN6",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT0.PEN6",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT0.PEN6"),
    },
    {
        label: "RSTXT0.PEN7",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT0.PEN7",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT0.PEN7"),
    },
    {
        label: "RSTXT0.PEN8",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT0.PEN8",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT0.PEN8"),
    },
    {
        label: "RSTXT0.PEN9",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT0.PEN9",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT0.PEN9"),
    },
    {
        label: "RSTXT0.PEN10",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT0.PEN10",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT0.PEN10"),
    },
    {
        label: "RSTXT0.PEN11",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT0.PEN11",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT0.PEN11"),
    },
    {
        label: "RSTXT0.PEN12",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT0.PEN12",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT0.PEN12"),
    },
    {
        label: "RSTXT0.PEN13",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT0.PEN13",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT0.PEN13"),
    },
    {
        label: "RSTXT0.PEN14",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT0.PEN14",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT0.PEN14"),
    },
    {
        label: "RSTXT0.PEN15",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT0.PEN15",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT0.PEN15"),
    },
    {
        label: "RSTXT1.PEN0",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT1.PEN0",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT1.PEN0"),
    },
    {
        label: "RSTXT1.PEN1",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT1.PEN1",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT1.PEN1"),
    },
    {
        label: "RSTXT1.PEN2",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT1.PEN2",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT1.PEN2"),
    },
    {
        label: "RSTXT1.PEN3",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/text.bas",
        signature: "CONST RSTXT1.PEN3",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSTXT1.PEN3"),
    },
    {
        label: "RSFW.BLACK",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.BLACK",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.BLACK"),
    },
    {
        label: "RSFW.BLUE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.BLUE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.BLUE"),
    },
    {
        label: "RSFW.BRIGHTBLUE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.BRIGHTBLUE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.BRIGHTBLUE"),
    },
    {
        label: "RSFW.RED",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.RED",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.RED"),
    },
    {
        label: "RSFW.MAGENTA",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.MAGENTA",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.MAGENTA"),
    },
    {
        label: "RSFW.MAUVE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.MAUVE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.MAUVE"),
    },
    {
        label: "RSFW.BRIGHTRED",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.BRIGHTRED",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.BRIGHTRED"),
    },
    {
        label: "RSFW.PURPLE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.PURPLE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.PURPLE"),
    },
    {
        label: "RSFW.BRIGHTMAGENTA",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.BRIGHTMAGENTA",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.BRIGHTMAGENTA"),
    },
    {
        label: "RSFW.GREEN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.GREEN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.GREEN"),
    },
    {
        label: "RSFW.CYAN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.CYAN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.CYAN"),
    },
    {
        label: "RSFW.SKYBLUE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.SKYBLUE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.SKYBLUE"),
    },
    {
        label: "RSFW.YELLOW",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.YELLOW",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.YELLOW"),
    },
    {
        label: "RSFW.WHITE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.WHITE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.WHITE"),
    },
    {
        label: "RSFW.PASTELBLUE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.PASTELBLUE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.PASTELBLUE"),
    },
    {
        label: "RSFW.ORANGE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.ORANGE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.ORANGE"),
    },
    {
        label: "RSFW.PINK",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.PINK",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.PINK"),
    },
    {
        label: "RSFW.PASTERMAGENTA",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.PASTERMAGENTA",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.PASTERMAGENTA"),
    },
    {
        label: "RSFW.BRIGHTGREEN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.BRIGHTGREEN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.BRIGHTGREEN"),
    },
    {
        label: "RSFW.SEAGREEN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.SEAGREEN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.SEAGREEN"),
    },
    {
        label: "RSFW.BRIGHTCYAN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.BRIGHTCYAN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.BRIGHTCYAN"),
    },
    {
        label: "RSFW.LIME",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.LIME",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.LIME"),
    },
    {
        label: "RSFW.PASTELGREEN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.PASTELGREEN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.PASTELGREEN"),
    },
    {
        label: "RSFW.PASTELCYAN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.PASTELCYAN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.PASTELCYAN"),
    },
    {
        label: "RSFW.BRIGHTYELLOW",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.BRIGHTYELLOW",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.BRIGHTYELLOW"),
    },
    {
        label: "RSFW.PASTELYELLOW",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.PASTELYELLOW",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.PASTELYELLOW"),
    },
    {
        label: "RSFW.BRIGHTWHITE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSFW.BRIGHTWHITE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSFW.BRIGHTWHITE"),
    },
    {
        label: "RSHW.BLACK",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.BLACK",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.BLACK"),
    },
    {
        label: "RSHW.BLUE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.BLUE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.BLUE"),
    },
    {
        label: "RSHW.BRIGHTBLUE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.BRIGHTBLUE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.BRIGHTBLUE"),
    },
    {
        label: "RSHW.RED",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.RED",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.RED"),
    },
    {
        label: "RSHW.MAGENTA",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.MAGENTA",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.MAGENTA"),
    },
    {
        label: "RSHW.MAUVE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.MAUVE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.MAUVE"),
    },
    {
        label: "RSHW.BRIGHTRED",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.BRIGHTRED",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.BRIGHTRED"),
    },
    {
        label: "RSHW.PURPLE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.PURPLE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.PURPLE"),
    },
    {
        label: "RSHW.BRIGHTMAGENTA",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.BRIGHTMAGENTA",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.BRIGHTMAGENTA"),
    },
    {
        label: "RSHW.GREEN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.GREEN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.GREEN"),
    },
    {
        label: "RSHW.CYAN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.CYAN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.CYAN"),
    },
    {
        label: "RSHW.SKYBLUE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.SKYBLUE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.SKYBLUE"),
    },
    {
        label: "RSHW.YELLOW",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.YELLOW",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.YELLOW"),
    },
    {
        label: "RSHW.WHITE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.WHITE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.WHITE"),
    },
    {
        label: "RSHW.PASTELBLUE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.PASTELBLUE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.PASTELBLUE"),
    },
    {
        label: "RSHW.ORANGE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.ORANGE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.ORANGE"),
    },
    {
        label: "RSHW.PINK",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.PINK",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.PINK"),
    },
    {
        label: "RSHW.PASTERMAGENTA",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.PASTERMAGENTA",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.PASTERMAGENTA"),
    },
    {
        label: "RSHW.BRIGHTGREEN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.BRIGHTGREEN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.BRIGHTGREEN"),
    },
    {
        label: "RSHW.SEAGREEN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.SEAGREEN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.SEAGREEN"),
    },
    {
        label: "RSHW.BRIGHTCYAN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.BRIGHTCYAN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.BRIGHTCYAN"),
    },
    {
        label: "RSHW.LIME",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.LIME",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.LIME"),
    },
    {
        label: "RSHW.PASTELGREEN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.PASTELGREEN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.PASTELGREEN"),
    },
    {
        label: "RSHW.PASTELCYAN",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.PASTELCYAN",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.PASTELCYAN"),
    },
    {
        label: "RSHW.BRIGHTYELLOW",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.BRIGHTYELLOW",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.BRIGHTYELLOW"),
    },
    {
        label: "RSHW.PASTELYELLOW",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.PASTELYELLOW",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.PASTELYELLOW"),
    },
    {
        label: "RSHW.BRIGHTWHITE",
        kind: vscode.CompletionItemKind.Variable,
        detail: "cpcrslib/video.bas",
        signature: "CONST RSHW.BRIGHTWHITE",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("RSHW.BRIGHTWHITE"),
    }
];