import * as vscode from 'vscode';
import { AbascCompletionInfo } from './abasccompletioninfo';

export const CPCTeleraInfo: AbascCompletionInfo[] = [
{
        label: "cpctakpDigiDrumStatus",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctakpDigiDrumStatus",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctakpDigiDrumStatus"),
    },
    {
        label: "cpctakpMusicInit",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctakpMusicInit(songdata)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctakpMusicInit(songdata)"),
    },
    {
        label: "cpctakpMusicPlay",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctakpMusicPlay",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctakpMusicPlay"),
    },
    {
        label: "cpctakpSetFadeVolume",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctakpSetFadeVolume(fadelevel)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctakpSetFadeVolume(fadelevel)"),
    },
    {
        label: "cpctakpSFXGetInstrument",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctakpSFXGetInstrument(channel)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctakpSFXGetInstrument(channel)"),
    },
    {
        label: "cpctakpSFXInit",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctakpSFXInit(songdata)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctakpSFXInit(songdata)"),
    },
    {
        label: "cpctakpSFXPlay",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctakpSFXPlay(sfxnum, vol, note, nspeed, invertedpitch, channelbitmask)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctakpSFXPlay(sfxnum, vol, note, nspeed, invertedpitch, channelbitmask)"),
    },
    {
        label: "cpctakpSFXStop",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctakpSFXStop(chbitmask)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctakpSFXStop(chbitmask)"),
    },
    {
        label: "cpctakpSFXStopAll",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctakpSFXStopAll",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctakpSFXStopAll"),
    },
    {
        label: "cpctakpSongLoopTimes",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctakpSongLoopTimes",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctakpSongLoopTimes"),
    },
    {
        label: "cpctakpStop",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctakpStop",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctakpStop"),
    },
    {
        label: "cpctGetBit",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctGetBit(array$, index)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctGetBit(array$, index)"),
    },
    {
        label: "cpctGet2Bits",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctGet2Bits(array$, index)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctGet2Bits(array$, index)"),
    },
    {
        label: "cpctGet4Bits",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctGet4Bits(array$, index)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctGet4Bits(array$, index)"),
    },
    {
        label: "cpctGet6Bits",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctGet6Bits(array$, index)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctGet6Bits(array$, index)"),
    },
    {
        label: "cpctSetBit",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSetBit(array$, value, index)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSetBit(array$, value, index)"),
    },
    {
        label: "cpctSet2Bits",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSet2Bits(array$, value, index)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSet2Bits(array$, value, index)"),
    },
    {
        label: "cpctSet4Bits",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSet4Bits(array$, value, index)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSet4Bits(array$, value, index)"),
    },
    {
        label: "cpctSet6Bits",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSet6Bits(array$, value, index)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSet6Bits(array$, value, index)"),
    },
    {
        label: "cpctetmDrawTileBox2x4",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctetmDrawTileBox2x4(x, y, w, h, mapw, videomem, timemap)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctetmDrawTileBox2x4(x, y, w, h, mapw, videomem, timemap)"),
    },
    {
        label: "cpctetmDrawTilemap2x4f",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctetmDrawTilemap2x4f(vieww, viewh, vmem, tiles)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctetmDrawTilemap2x4f(vieww, viewh, vmem, tiles)"),
    },
    {
        label: "cpctetmDrawTilemap4x8ag",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctetmDrawTilemap4x8ag(memaddress, tileids)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctetmDrawTilemap4x8ag(memaddress, tileids)"),
    },
    {
        label: "cpctetmDrawTilemap4x8agf",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctetmDrawTilemap4x8agf(memaddress, tileids)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctetmDrawTilemap4x8agf(memaddress, tileids)"),
    },
    {
        label: "cpctetmDrawTileRow2x4",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctetmDrawTileRow2x4(ntiles, pvideomem, ptmrow)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctetmDrawTileRow2x4(ntiles, pvideomem, ptmrow)"),
    },
    {
        label: "cpctetmSetTileset2x4",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctetmSetTileset2x4(tileset)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctetmSetTileset2x4(tileset)"),
    },
    {
        label: "cpctetmSetDrawTilemap4x8ag",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctetmSetDrawTilemap4x8ag(vieww, viewh, tilemapw, tiles)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctetmSetDrawTilemap4x8ag(vieww, viewh, tilemapw, tiles)"),
    },
    {
        label: "cpctetmSetDrawTilemap4x8agf",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctetmSetDrawTilemap4x8agf(vieww, viewh, tilemapw, tiles)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctetmSetDrawTilemap4x8agf(vieww, viewh, tilemapw, tiles)"),
    },
    {
        label: "cpctDisableFirmware",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctDisableFirmware",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDisableFirmware"),
    },
    {
        label: "cpctDisableLowerROM",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDisableLowerROM",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDisableLowerROM"),
    },
    {
        label: "cpctDisableUpperROM",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDisableUpperROM",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDisableUpperROM"),
    },
    {
        label: "cpctEnableLowerROM",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctEnableLowerROM",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctEnableLowerROM"),
    },
    {
        label: "cpctEnableUpperROM",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctEnableUpperROM",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctEnableUpperROM"),
    },
    {
        label: "cpctReenableFirmware",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctReenableFirmware",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctReenableFirmware"),
    },
    {
        label: "cpctRemoveInterruptHandler",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctRemoveInterruptHandler",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctRemoveInterruptHandler"),
    },
    {
        label: "cpctSetInterruptHandler",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSetInterruptHandler(cbaddress)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSetInterruptHandler(cbaddress)"),
    },
    {
        label: "cpctGetKeypressedAsASCII",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctGetKeypressedAsASCII",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctGetKeypressedAsASCII"),
    },
    {
        label: "cpctIsAnyKeyPressed",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctIsAnyKeyPressed",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctIsAnyKeyPressed"),
    },
    {
        label: "cpctIsAnyKeyPressedf",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctIsAnyKeyPressedf",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctIsAnyKeyPressedf"),
    },
    {
        label: "cpctIsKeyPressed",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctIsKeyPressed(keyid)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctIsKeyPressed(keyid)"),
    },
    {
        label: "cpctScanKeyboard",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctScanKeyboard",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctScanKeyboard"),
    },
    {
        label: "cpctScanKeyboardf",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctScanKeyboardf",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctScanKeyboardf"),
    },
    {
        label: "cpctScanKeyboardi",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctScanKeyboardi",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctScanKeyboardi"),
    },
    {
        label: "cpctScanKeyboardif",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctScanKeyboardif",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctScanKeyboardif"),
    },
    {
        label: "cpctMemcpy",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctMemcpy(toptr, fromptr, bytes)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctMemcpy(toptr, fromptr, bytes)"),
    },
    {
        label: "cpctMemset",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctMemset(arrayptr, value, bytes)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctMemset(arrayptr, value, bytes)"),
    },
    {
        label: "cpctMemsetf8",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctMemsetf8(arrayptr, value, bytes)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctMemsetf8(arrayptr, value, bytes)"),
    },
    {
        label: "cpctMemsetf64",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctMemsetf64(arrayptr, value, bytes)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctMemsetf64(arrayptr, value, bytes)"),
    },
    {
        label: "cpctMemsetf64i",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctMemsetf64i(arrayptr, value, bytes)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctMemsetf64i(arrayptr, value, bytes)"),
    },
    {
        label: "cpctPageMemory",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctPageMemory(bankvalue)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctPageMemory(bankvalue)"),
    },
    {
        label: "cpctSetStackLocation",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSetStackLocation(addr)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSetStackLocation(addr)"),
    },
    {
        label: "cpctWaitHalts",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctWaitHalts(halts)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctWaitHalts(halts)"),
    },
    {
        label: "cpctSRand",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSRand(seed)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSRand(seed)"),
    },
    {
        label: "cpctRand",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctRand",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctRand"),
    },
    {
        label: "cpctDrawSpriteBlended",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawSpriteBlended(vmem, w, h, sprite)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawSpriteBlended(vmem, w, h, sprite)"),
    },
    {
        label: "cpctSetBlendMode",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSetBlendMode(bmode) ASM",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSetBlendMode(bmode)"),
    },
    {
        label: "cpctDrawSpriteColorizeM0",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawSpriteColorizeM0(sprite, vmem, w, h, rplcpat)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawSpriteColorizeM0(sprite, vmem, w, h, rplcpat)"),
    },
    {
        label: "cpctDrawSpriteColorizeM1",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawSpriteColorizeM1(sprite, vmem, w, h, rplcpat)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawSpriteColorizeM1(sprite, vmem, w, h, rplcpat)"),
    },
    {
        label: "cpctDrawSpriteMaskedAlignedColorizeM0",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawSpriteMaskedAlignedColorizeM0(sprite, vmem, w, h, masktable, rplcpat)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawSpriteMaskedAlignedColorizeM0(sprite, vmem, w, h, masktable, rplcpat)"),
    },
    {
        label: "cpctDrawSpriteMaskedAlignedColorizeM1",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawSpriteMaskedAlignedColorizeM1(sprite, vmem, w, h, masktable, rplcpat)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawSpriteMaskedAlignedColorizeM1(sprite, vmem, w, h, masktable, rplcpat)"),
    },
    {
        label: "cpctDrawSpriteMaskedColorizeM0",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawSpriteMaskedColorizeM0(sprite, vmem, w, h, rplcpat)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawSpriteMaskedColorizeM0(sprite, vmem, w, h, rplcpat)"),
    },
    {
        label: "cpctDrawSpriteMaskedColorizeM1",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawSpriteMaskedColorizeM1(sprite, vmem, w, h, rplcpat)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawSpriteMaskedColorizeM1(sprite, vmem, w, h, rplcpat)"),
    },
    {
        label: "cpctSpriteColorizeM0",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSpriteColorizeM0(rplcpat, size, sprite)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSpriteColorizeM0(rplcpat, size, sprite)"),
    },
    {
        label: "cpctSpriteColorizeM1",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSpriteColorizeM1(rplcpat, size, sprite)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSpriteColorizeM1(rplcpat, size, sprite)"),
    },
    {
        label: "cpctSpriteMaskedColorizeM0",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSpriteMaskedColorizeM0(rplcpat, size, sprite)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSpriteMaskedColorizeM0(rplcpat, size, sprite)"),
    },
    {
        label: "cpctSpriteMaskedColorizeM1",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSpriteMaskedColorizeM1(rplcpat, size, sprite)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSpriteMaskedColorizeM1(rplcpat, size, sprite)"),
    },
    {
        label: "cpctDrawTileAligned2x4f",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawTileAligned2x4f(tile, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawTileAligned2x4f(tile, vmem)"),
    },
    {
        label: "cpctDrawTileAligned2x8",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawTileAligned2x8(tile, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawTileAligned2x8(tile, vmem)"),
    },
    {
        label: "cpctDrawTileAligned2x8f",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawTileAligned2x8f(tile, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawTileAligned2x8f(tile, vmem)"),
    },
    {
        label: "cpctDrawTileAligned4x4f",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawTileAligned4x4f(tile, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawTileAligned4x4f(tile, vmem)"),
    },
    {
        label: "cpctDrawTileAligned4x8",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawTileAligned4x8(tile, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawTileAligned4x8(tile, vmem)"),
    },
    {
        label: "cpctDrawTileAligned4x8f",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawTileAligned4x8f(tile, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawTileAligned4x8f(tile, vmem)"),
    },
    {
        label: "cpctDrawTileGrayCode2x8af",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawTileGrayCode2x8af(tile, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawTileGrayCode2x8af(tile, vmem)"),
    },
    {
        label: "cpctDrawTileZigZagGrayCode4x8af",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawTileZigZagGrayCode4x8af(tile, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawTileZigZagGrayCode4x8af(tile, vmem)"),
    },
    {
        label: "cpctDrawToSpriteBuffer",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawToSpriteBuffer(bufferw, buffer, w, h, sprite)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawToSpriteBuffer(bufferw, buffer, w, h, sprite)"),
    },
    {
        label: "cpctDrawToSpriteBufferMasked",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawToSpriteBufferMasked(bufferw, buffer, w, h, sprite)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawToSpriteBufferMasked(bufferw, buffer, w, h, sprite)"),
    },
    {
        label: "cpctDrawToSpriteBufferMaskedAlignedTable",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawToSpriteBufferMaskedAlignedTable(bufferw, buffer, w, h, sprite, masktable)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawToSpriteBufferMaskedAlignedTable(bufferw, buffer, w, h, sprite, masktable)"),
    },
    {
        label: "cpctDrawSpriteHFlipM0",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawSpriteHFlipM0(sprite, vmem, w, h)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawSpriteHFlipM0(sprite, vmem, w, h)"),
    },
    {
        label: "cpctDrawSpriteHFlipM1",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawSpriteHFlipM1(sprite, vmem, w, h)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawSpriteHFlipM1(sprite, vmem, w, h)"),
    },
    {
        label: "cpctDrawSpriteHFlipM2",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawSpriteHFlipM2(sprite, vmem, w, h)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawSpriteHFlipM2(sprite, vmem, w, h)"),
    },
    {
        label: "cpctDrawSpriteVFlip",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawSpriteVFlip(sprite, vmem, w, h)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawSpriteVFlip(sprite, vmem, w, h)"),
    },
    {
        label: "cpctDrawSpriteVFlipMasked",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawSpriteVFlipMasked(sprite, vmem, w, h)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawSpriteVFlipMasked(sprite, vmem, w, h)"),
    },
    {
        label: "cpctGetBottomLeftPtr",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctGetBottomLeftPtr(vmem, h)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctGetBottomLeftPtr(vmem, h)"),
    },
    {
        label: "cpctHFlipSpriteM0",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctHFlipSpriteM0(w, h, sprite)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctHFlipSpriteM0(w, h, sprite)"),
    },
    {
        label: "cpctHfFlipSpriteM0r",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctHfFlipSpriteM0r(sprite, w, h)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctHfFlipSpriteM0r(sprite, w, h)"),
    },
    {
        label: "cpctHFlipSpriteM1",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctHFlipSpriteM1(w, h, sprite)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctHFlipSpriteM1(w, h, sprite)"),
    },
    {
        label: "cpctHFlipSpriteM1r",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctHFlipSpriteM1r(sprite, w, h)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctHFlipSpriteM1r(sprite, w, h)"),
    },
    {
        label: "cpctHFlipSpriteM2",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctHFlipSpriteM2(w, h, sprite)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctHFlipSpriteM2(w, h, sprite)"),
    },
    {
        label: "cpctHFlipSpriteM2r",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctHFlipSpriteM2r(sprite, w, h)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctHFlipSpriteM2r(sprite, w, h)"),
    },
    {
        label: "cpctHFlipSpriteMaskedM0",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctHFlipSpriteMaskedM0(w, h, sprite)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctHFlipSpriteMaskedM0(w, h, sprite)"),
    },
    {
        label: "cpctHFlipSpriteMaskedM1",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctHFlipSpriteMaskedM1(w, h, sprite)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctHFlipSpriteMaskedM1(w, h, sprite)"),
    },
    {
        label: "cpctHFlipSpriteMaskedM2",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctHFlipSpriteMaskedM2(w, h, sprite)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctHFlipSpriteMaskedM2(w, h, sprite)"),
    },
    {
        label: "cpctGetScreenToSprite",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctGetScreenToSprite(vmem, sprite, w, h)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctGetScreenToSprite(vmem, sprite, w, h)"),
    },
    {
        label: "cpctDrawSolidBox",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawSolidBox(address, cpattern, w, h)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawSolidBox(address, cpattern, w, h)"),
    },
    {
        label: "cpctDrawSprite",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawSprite(sprite, videopos, spwidth, spheight)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawSprite(sprite, videopos, spwidth, spheight)"),
    },
    {
        label: "cpctDrawSpriteMasked",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawSpriteMasked(sprite, vmem, w, h)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawSpriteMasked(sprite, vmem, w, h)"),
    },
    {
        label: "cpctDrawSpriteMaskedAlignedTable",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawSpriteMaskedAlignedTable(sprite, vmem, w, h, masktable)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawSpriteMaskedAlignedTable(sprite, vmem, w, h, masktable)"),
    },
    {
        label: "cpctPen2pixelPatternM0",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctPen2pixelPatternM0(pnum)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctPen2pixelPatternM0(pnum)"),
    },
    {
        label: "cpctPen2pixelPatternM1",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctPen2pixelPatternM1(pnum)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctPen2pixelPatternM1(pnum)"),
    },
    {
        label: "cpctPen2TwoPixelPatternM0",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctPen2TwoPixelPatternM0(newpen, oldpen)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctPen2TwoPixelPatternM0(newpen, oldpen)"),
    },
    {
        label: "cpctPen2TwoPixelPatternM1",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctPen2TwoPixelPatternM1(newpen, oldpen)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctPen2TwoPixelPatternM1(newpen, oldpen)"),
    },
    {
        label: "cpctpx2byteM0",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctpx2byteM0(px0, px1)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctpx2byteM0(px0, px1)"),
    },
    {
        label: "cpctpx2byteM1",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctpx2byteM1(px0, px1, px2, px3)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctpx2byteM1(px0, px1, px2, px3)"),
    },
    {
        label: "cpctDrawCharM0",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawCharM0(vmem, chnum)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawCharM0(vmem, chnum)"),
    },
    {
        label: "cpctDrawCharM1",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawCharM1(vmem, chnum)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawCharM1(vmem, chnum)"),
    },
    {
        label: "cpctDrawCharM2",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawCharM2(vmem, chnum)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawCharM2(vmem, chnum)"),
    },
    {
        label: "cpctDrawStringM0",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawStringM0(s$, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawStringM0(s$, vmem)"),
    },
    {
        label: "cpctDrawStringM1",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawStringM1(s$, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawStringM1(s$, vmem)"),
    },
    {
        label: "cpctDrawStringM2",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctDrawStringM2(s$, vmem)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctDrawStringM2(s$, vmem)"),
    },
    {
        label: "cpctSetDrawCharM0",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSetDrawCharM0(fg, bg)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSetDrawCharM0(fg, bg)"),
    },
    {
        label: "cpctSetDrawCharM1",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSetDrawCharM1(fg, bg)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSetDrawCharM1(fg, bg)"),
    },
    {
        label: "cpctSetDrawCharM2",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSetDrawCharM2(fg, bg)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSetDrawCharM2(fg, bg)"),
    },
    {
        label: "cpctClearScreen",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctClearScreen(color)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctClearScreen(color)"),
    },
    {
        label: "cpctClearScreenf64",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctClearScreenf64(color)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctClearScreenf64(color)"),
    },
    {
        label: "cpctCount2VSYNC",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctCount2VSYNC",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctCount2VSYNC"),
    },
    {
        label: "cpctFW2HW",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctFW2HW(paldir, items)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctFW2HW(paldir, items)"),
    },
    {
        label: "cpctGetHWColour",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctGetHWColour(fwcol)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctGetHWColour(fwcol)"),
    },
    {
        label: "cpctGetScreenPtr",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctGetScreenPtr(vstart, x, y)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctGetScreenPtr(vstart, x, y)"),
    },
    {
        label: "cpctGetVSYNCStatus",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "FUNCTION cpctGetVSYNCStatus",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctGetVSYNCStatus"),
    },
    {
        label: "cpctSetBorder",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSetBorder(hwcolor)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSetBorder(hwcolor)"),
    },
    {
        label: "cpctSetCRTCReg",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSetCRTCReg(regnum, newval)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSetCRTCReg(regnum, newval)"),
    },
    {
        label: "cpctSetPALColour",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSetPALColour(ipen, hwcolor)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSetPALColour(ipen, hwcolor)"),
    },
    {
        label: "cpctSetPalette",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSetPalette(palptr, items)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSetPalette(palptr, items)"),
    },
    {
        label: "cpctSetVideoMemoryOffset",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSetVideoMemoryOffset(offset)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSetVideoMemoryOffset(offset)"),
    },
    {
        label: "cpctSetVideoMemoryPage",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSetVideoMemoryPage(pageid)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSetVideoMemoryPage(pageid)"),
    },
    {
        label: "cpctSetVideoMode",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctSetVideoMode(vmode)",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctSetVideoMode(vmode)"),
    },
    {
        label: "cpctWaitVSYNC",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctWaitVSYNC",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctWaitVSYNC"),
    },
    {
        label: "cpctWaitVSYNCStart",
        kind: vscode.CompletionItemKind.Function,
        detail: "cpctelera/",
        signature: "SUB cpctWaitVSYNCStart",
        documentation: new vscode.MarkdownString(""),
        insertText: new vscode.SnippetString("cpctWaitVSYNCStart"),
    }
];